version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewProjDocTypeTestProject
  gitServerName: SanthoshKToken7D
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
- name: CustomPackage
  version: "1.0"
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
services:
- serviceName: project.newprojdoctypetest.integrations:getDate
  packages:
  - name: NewProjDocTypeTestProject
    version: "1.0"
  - name: CustomPackage
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1120
- serviceName: pub.math:randomDouble
  packages:
  - name: WmPublic
    version: 11.1.0.0.1120
