version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewProjDocTypeTestProject
  gitServerName: SanthoshKToken7D
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.newprojdoctypetest.integrations:random
  packages:
  - name: NewProjDocTypeTestProject
    version: "1.0"
- serviceName: pub.math:randomDouble
  packages:
  - name: WmPublic
    version: 11.1.0.0.1120
